name: Build and deploy Go application to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build your Go application
        run: go build -o myapp ./

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: go-app
          path: ./myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: go-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'gos3test'  # Replace with your Azure Web App name
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7F91C14D7B0E4A7EAB4DF5866C3C5DD2 }}
          package: .
